### PR TITLE
Fix for rendering on server

### PR DESCRIPTION
**Pull request by TriPSs**
Require chart.js in componentDidMount so it won't give errors on the server.

### CODE REVIEW

**Comment by jerairrest** [comment]
Not exporting the defaults as well as the chart instance seems like a significant breaking change to functionality. Can you write some tests to prove this isn't? Thanks a ton for the PR by the way!

**Comment by TriPSs** [comment]
I removed those because you can't export them any more, i did check the examples and they all kept working. 

Will update the PR soon so it won't crash Travis

**Comment by thomaslindstrom** [comment]
:+1:

**Comment by jerairrest** [comment]
Closing since this is almost a year old.

**Pull request closed without merging**
