### PR TITLE
Fix issue #324: Re-using the same dataset in another chart (for example, in tabs) causes a failure.

### PR DESCRIPTION
**Pull request by bdwade100**
This pull request fixes issue #324.

### CODE REVIEW

**Comment by bdwade100** [comment]
Let me know if you have any questions.

**Comment by bdwade100** [comment]
Please review this pull request. It has been in production code since Oct 2018.

Let me know if you have any questions. Thanks!

**Comment by bdwade100** [comment]
@jerairrest , thanks for considering this pull request. If it would help, I can add additional comments to the code or review them with you. I did a force push so that this pull request is one change from your current branch.

**Comment by bdwade100** [comment]
Hi @jerairrest , I haven't heard anything back from you on my previous posts to review this pull request, so I'm getting the sense that you're not interested in it.

I'd consider it a personal favor if you would let me know either way, and I can stop sending requests to review the pull request which I'm sure you can appreciate.

Respectfully,
Brad

**Comment by jerairrest** [comment]
Hey Brad!

I apologise for being MIA from this project. :( I'll attempt to look at this pull request tonight. 

Thanks for contributing

Jer

**Comment by bdwade100** [comment]
Thanks, Jeremy, for looking at my PR and merging it.

Brad

**Pull request merged**
