### PR TITLE
klk1010: Update dependencies vs devDependencies in package.json

### PR DESCRIPTION
**Pull request by klk1010**
`package.json` `devDependencies` and `dependencies` are inverted.

### CODE REVIEW

**Comment by jerairrest** [comment]
Thank's for the PR but I'm a tad confused what trouble you're having to come to this conclusion. Can you explain why you feel like the package.json is incorrect?

**Comment by klk1010** [comment]
I was prompted to address this because I encountered a compilation error warning - that chart.js could not be found -in a prototype project that has react-chartjs-2 v 2.6.4 as a dependency. I've been going into my node_modules dir after every fresh npm install, going into react-chartjs-2 package.json and adjusting it to have chart.js as a dependency. They aren't inverted, there are just some devDependencies I believe should be in dependencies instead. I'll update my PR.

npm version: 5.5.1
node version: 8.5.0

**Comment by klk1010** [comment]
PR Updated

**Comment by klk1010** [comment]
If anyone else runs into the error chart.js not found, in the meantime I resolved this by adding it as its own dependency to my project.

**Comment by jerairrest** [comment]
Yep! Chart.js is a peer dependancy to this package. Thanks again for the contribution.

**Pull request closed without merging**
