### PR TITLE
rename chart_instance to chartInstance

### PR DESCRIPTION
**Pull request by jerairrest**
@benmccann

### CODE REVIEW

**Comment by AbraaoAlves** [comment]
You forgot to change this in typescript file: https://github.com/jerairrest/react-chartjs-2/blob/master/index.d.ts#L37

This broken typescript app.

**Comment by benmccann** [comment]
Fixed https://github.com/jerairrest/react-chartjs-2/commit/5a362c6da9e54926970ee33e19db11ff62a26331. Thanks for reporting

**Comment by AbraaoAlves** [comment]
Thank you for the speed. When will this be available in npm?

**Comment by benmccann** [comment]
I'll leave that question to @jerairrest

**Comment by tengattack** [comment]
Hi, the new variable rename should publish to npm.
Currently it is old name and unable to use the new variable rename.

Thanks

**Comment by jerairrest** [comment]
This should be pushed now.

**Pull request merged**
