### PR TITLE
Replaced findDomNode with ref in order to use react-test-renderer for snapshot testing with storybook

### PR DESCRIPTION
**Pull request by acailly**
I tried to use storyshots which uses react-test-renderer for snapshot testing.
Unfortunately findDomNode is not supported by react-test-renderer, but there is an alternative that works well: use a React ref.

More info on this incompatibility here: facebook/react#7371

I've included another PR of mine in order to be able to test on windows: https://github.com/gor181/react-chartjs-2/pull/141

### CODE REVIEW

**Comment by jerairrest** [comment]
Thanks for the contribution!

**Comment by xogeny** [comment]
I'm unclear, does this actually allow snapshot testing.  When I try to use `react-test-renderer` with version `2.5.1`, I still get errors like this from deep inside `react-test-renderer` implying that it is unhappy when it isn't running in a browser.  Am I missing something?

```
 ● Plots - No Points

    TypeError: Cannot read property 'length' of null

      at Object.acquireContext (node_modules/chart.js/src/platforms/platform.dom.js:189:19)
      at Chart.construct (node_modules/chart.js/src/core/core.controller.js:72:27)
      at new Chart (node_modules/chart.js/src/core/core.js:7:8)
      at ChartComponent.renderChart (node_modules/react-chartjs-2/lib/index.js:303:29)
      at ChartComponent.componentDidMount (node_modules/react-chartjs-2/lib/index.js:124:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:263:11
```

**Comment by MOZGIII** [comment]
Same error. Any idea on how to fix it?

**Comment by glubb92** [comment]
We are running into the same issue. Does somebody have an idea how to fix it?

**Pull request merged**
